### ISSUE TITLE
password links fail

### ISSUE THREAD

**Issue by Huge** [dylnbk/quietly#1]
I have tried the Password tab, but it failed to copy the [generated link](https://quietly.streamlit.app/~/+/#774b2284d1aa464a9188a01f5c26bb33) on click and then failed to reveal the passphrase when I right-click copied it and pasted to another browser.

**Comment by dylnbk** [comment]
Thanks for checking out the app!

The on-click is not actually a button to copy the link, sorry for the confusion. It is a 'header' link and automatically generated by Streamlit, I might have to look and see if there is a parameter for me to remove it.

I have tried to replicate the bug where copying the public key into the reveal tab fails to show the passphrase, but it works for me across all browsers.

Please make sure that the generated public key is copied correctly into your clipboard and it is the first time revealing the passphrase, as all database entries are deleted as soon as you reveal the message.
